{
 "title": "Power Systems HMC system view",
 "description": "Nextract HMC PCM data system view",
 "tags": [ "HMC" ],
 "time": {
  "from": "now/d",
  "now": false,
  "to": "now"
 },
 "templating": {
  "list": [
   {
    "name": "ManagedSystem",
    "query": "SHOW TAG VALUES FROM \"Server\" WITH KEY = \"lpar\""
   },
   {
    "name": "Partition",
    "query": "SHOW TAG VALUES FROM \"LPAR\" WITH KEY = \"lpar\""
   }
  ]
 },
 "panels": [
  { "title": "Energy and Thermal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$ManagedSystem thermal data",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "C°" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Energy",
     "select": [
      [
       { "params": [ "cpu0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU_0" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU_1" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Energy",
     "query": "SELECT \"inlet\" AS \"Turbine Inlet\" FROM \"Energy\" WHERE (\"host\" =~ /^$ManagedSystem$/) AND $timeFilter GROUP BY \"host\" fill(null)",
     "select": [
      [
       { "params": [ "inlet" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Turbine Inlet" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "Energy consumed by $ManagedSystem",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Watt" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Energy",
     "query": "SELECT mean(\"watts\") FROM \"Energy\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Energy" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  { "title": "$ManagedSystem Memory Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "LPARs Configured Memory",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "alias": "$tag_lpar",
     "groupBy": [
      { "params": [ "lpar" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LPAR",
     "select": [
      [
       { "params": [ "mem_conf" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Memory configured" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "lpar", "operator": "=~", "value": "/^$Partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 11 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Server",
     "select": [
      [
       { "params": [ "mem_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lpar", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "Configured Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 11 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Server",
     "select": [
      [
       { "params": [ "mem_conf" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lpar", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "Vios Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Server",
     "select": [
      [
       { "params": [ "vios_mem_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lpar", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "Asigned Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 14 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Server",
     "select": [
      [
       { "params": [ "mem_inVM" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lpar", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "Avaliable Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 14 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Server",
     "select": [
      [
       { "params": [ "mem_avail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lpar", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "Vios Configured Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 14 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Server",
     "select": [
      [
       { "params": [ "vios_mem_conf" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lpar", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  { "title": "$ManagedSystem Processors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "ManagedSystem" },
  {
   "title": "$ManagedSystem Processor Usage by Partition",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "alias": "$tag_lpar",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionProcessor",
     "query": "SELECT \"cpu_used\" FROM \"LPAR\" WHERE (\"lpar\" =~ /^$Partition$/) AND $timeFilter GROUP BY lpar",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "", "key": "name", "operator": "=", "value": "UtilizedProcUnits" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "partition", "operator": "=~", "value": "/^$Partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Vios Used CPU %",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Server",
     "query": "SELECT last(cpu_used / cpu_total) AS \"cpu_used\" FROM \"Server\" WHERE (\"lpar\" =~ /^$ManagedSystem$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "vios_cpu_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*100 / vios_cpu_entitled" ], "type": "math" },
       { "params": [ "cpu_used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "lpar", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "System Used CPU %",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Server",
     "query": "SELECT last(cpu_used / cpu_total) AS \"cpu_used\" FROM \"Server\" WHERE (\"lpar\" =~ /^$ManagedSystem$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*100 / cpu_total" ], "type": "math" },
       { "params": [ "cpu_used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "lpar", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "System CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Server",
     "query": "SELECT last(cpu_used / cpu_total) AS \"cpu_used\" FROM \"Server\" WHERE (\"lpar\" =~ /^$ManagedSystem$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "cpu_used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "lpar", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Server",
     "select": [
      [
       { "params": [ "cpu_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "lpar", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  { "title": "$ManagedSystem Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }, "repeat": "ManagedSystem" },
  {
   "title": "$ManagedSystem VIOS Physical Fiber Channel Adapters write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_lpar",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SystemFiberChannelAdapters",
     "query": "SELECT vios_fc_rbytes FROM \"Server\" WHERE (\"lpar\" =~ /^$ManagedSystem$/) AND $timeFilter GROUP BY lpar",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/writeByt/" }
     ]
    }
   ]
  },
  {
   "title": "$ManagedSystem SEA transfered bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "lpar" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Server",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "vios_net_wbytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lpar", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    },
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "lpar" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Server",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "vios_net_rbytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "lpar", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "LPAR transfered bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_lpar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "lpar" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LPAR",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "net_wbytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lpar", "operator": "=~", "value": "/^$Partition$/" }
     ]
    }
   ]
  },
  {
   "title": "LPAR recibed bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_lpar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "lpar" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LPAR",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "net_rbytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lpar", "operator": "=~", "value": "/^$Partition$/" }
     ]
    }
   ]
  }
 ]
}